name: Test CI

on:
  push:
    branches:
      - second

jobs:
  test-job:
    name: Test Job for the second branch
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      run: |
        echo Hello there on the second branch!
